vel_x = 0;
vel_y = 0;
max_vel = 5;
current_vel = max_vel
stamina_vel = 50
stamina = 100
accel = 0.5;
friction = 0.050;
delay_time = 0.3
timer = delay_time * 60
spawn_object = obj_bullet;
global.metal = 0
global.healther = 100
global.maxhp = 100
draw_set_font(fnt_roboto_light)
invincible = false;
invincible_timer = 0
global.kills = 0
_wall = layer_tilemap_get_id("Tiles");
if (_wall == -1) show_debug_message("ОШИБКА: Слой Tiles не найден!");
global.saving = false
skin = 1
move_speed = 5
alarm[0] = 300
alarm[1] = 600
global.killsm = 0
global.killsu = 0
timet = 0
alarm[2] = 60
xm = 70
ym = 310-60
image_index = 1
global.defendhealther = 70
white = make_colour_rgb(255, 255, 255)
red = make_colour_rgb(255, 0, 0)
red_to_white = 255
decreasing = true
reder = make_colour_rgb(red_to_white, 0, 0)
alarm[3] = 120*2
alarm[1] = 60
blind_intensity = 0;
move_speed = 5
recoil_x = 0;
recoil_y = 0;
draw_x = x;
draw_y = y;
global.shake = 0;
global.flash_val = 0;
