kills = 0
speed = 3;
paused = false;
normal_speed = 1
YDAR = 2
image_angle = random_range(0, 360)
detection_range = 200;
flee_range = 150;
is_fleeing = false;
is_shaking = false;
shake_timer = 0;
shake_duration = 30;
shake_intensity = 3;
original_x = x;
original_y = y;
alarm[0] = random_range(0, 120)
enemies_healther = 1
AI = random_range(1, 2)